[project]
name = "ai-summer-school"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dotenv>=0.9.9",
    "ollama>=0.5.3",
    "openai>=1.106.1",
    "pydantic>=2.11.7",
    "pyniryo>=1.2.1",
]
